name: "Validate Gradle Wrapper"
on:
  push:
    paths:
      - 'gradlew'
      - 'gradlew.bat'
      - 'gradle/wrapper/'
  pull_request:
    paths:
      - 'gradlew'
      - 'gradlew.bat'
      - 'gradle/wrapper/'

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: gradle/wrapper-validation-action@v1
